before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
script: "bundle exec rspec spec"
notifications:
  email:
    - briandquinn@gmail.com
branches:
  only:
    - 1-1-stable
rvm:
  - 1.9.3
